// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sumsub.DataAccess;

#nullable disable

namespace Sumsub.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Sumsub.DataAccess.Models.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtMs")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExternalUserId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReviewResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SandboxMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewResultId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Sumsub.DataAccess.Models.ReviewResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModerationComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectLabels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewRejectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReviewResults");
                });

            modelBuilder.Entity("Sumsub.DataAccess.Models.Applicant", b =>
                {
                    b.HasOne("Sumsub.DataAccess.Models.ReviewResult", "ReviewResult")
                        .WithMany()
                        .HasForeignKey("ReviewResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewResult");
                });
#pragma warning restore 612, 618
        }
    }
}
